#!/bin/bash

set -e

OUTDIR=pubmlst
mkdir -p "$OUTDIR"
wget --no-clobber -P "$OUTDIR" http://pubmlst.org/data/dbases.xml 

for URL in $(grep '<url>' $OUTDIR/dbases.xml); do
#  echo $URL
  URL=${URL//<url>}
  URL=${URL//<\/url>}
#  echo ${URL: -4}
  if [ ${URL:(-4)} = ".txt" ]; then
    PROFILE=$(basename $URL .txt)
    echo "# $PROFILE "
    PROFILEDIR="$OUTDIR/$PROFILE"
    echo "mkdir -p '$PROFILEDIR'"
    echo "(cd '$PROFILEDIR' && wget '$URL')"
  elif [ ${URL:(-4)} = ".tfa" ]; then
    echo "(cd '$PROFILEDIR' && wget '$URL')"
  fi 
done
